// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAksx3_Dq6H1oKxcRxsP_UyaPzgGdUt8i0',
    appId: '1:253638848272:web:a51f9955bb471c9f083f95',
    messagingSenderId: '253638848272',
    projectId: 'login-app-2a820',
    authDomain: 'login-app-2a820.firebaseapp.com',
    storageBucket: 'login-app-2a820.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpcfvMEYg774Wgnt38IU_VTOTu7GAJtUQ',
    appId: '1:253638848272:android:a85cd1755737eae5083f95',
    messagingSenderId: '253638848272',
    projectId: 'login-app-2a820',
    storageBucket: 'login-app-2a820.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFX7Tz1t78q-FQmbkddoPca1A3x_FvpuI',
    appId: '1:253638848272:ios:1ad616dfefd61cc8083f95',
    messagingSenderId: '253638848272',
    projectId: 'login-app-2a820',
    storageBucket: 'login-app-2a820.appspot.com',
    iosClientId: '253638848272-2t5p4u4c78283kn4m12gbl9j4t7qn6qu.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFX7Tz1t78q-FQmbkddoPca1A3x_FvpuI',
    appId: '1:253638848272:ios:1ad616dfefd61cc8083f95',
    messagingSenderId: '253638848272',
    projectId: 'login-app-2a820',
    storageBucket: 'login-app-2a820.appspot.com',
    iosClientId: '253638848272-2t5p4u4c78283kn4m12gbl9j4t7qn6qu.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginapp',
  );
}
